# This is a basic workflow to help you get started with Actions
name: web-production
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ production ]
    paths:
      - 'web/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario'
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build production web
        id: build-app
        run: |
          docker build -f deploy/script/Dockerfile -t deploy ./
          docker run -v /var/run/docker.sock:/var/run/docker.sock:rw \
          -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_REGION="${{ secrets.AWS_REGION }}" \
          -e AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          -e CLUSTER_NAME=${{ env.CLUSTER_NAME_PRODUCTION }} \
          -e SERVICE=web \
          -e IMAGE_TAG=production.${{ github.sha }} \
          -e NAMESPACE=production \
          -e ENVIRONMENT=production \
          deploy
