---
  - name: add nginx ppa
    apt_repository: repo='ppa:nginx/stable'

  - name: update apt-get
    apt: update_cache=yes cache_valid_time=3600

  - name: install nginx
    apt: pkg=nginx state=present

  - name: copy nginx.conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
    tags:
      - nginx

  - name: setup nginx host file dirs
    file: name=/etc/nginx/{{ item }} state=directory owner=root group=root
    with_items:
      - sites-available
      - sites-enabled

  - name: ensure default nginx has been deleted
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
    tags:
      - nginx
