version: '3.6'
services:
  mongo:
    container_name: base-mongo
    image: mongo:4.4
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /config/mongo-keyfile
        chown 999:999 /config/mongo-keyfile
        exec docker-entrypoint.sh $$@
    command: mongod --replSet rs --bind_ip_all --keyFile config/mongo-keyfile --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - base
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/src/config:/config
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  mongo-replicator:
    container_name: base-mongo-replicator
    build: ./api/mongo-replicator
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=rs
    networks:
      - base
    depends_on:
      - mongo
  redis:
    container_name: base-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - base
    ports:
      - 6379:6379
  api:
    container_name: base-api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - base
    volumes:
      - ./api/src:/app/src
    ports:
      - 3001:3001
    depends_on:
      - redis
      - mongo-replicator
  migrator:
    container_name: base-migrator
    build:
      context: ./api
      dockerfile: Dockerfile.migrator
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - base
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo-replicator
  scheduler:
    container_name: base-scheduler
    build:
      context: ./api
      dockerfile: Dockerfile.scheduler
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - base
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo-replicator
  web:
    container_name: base-web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    networks:
      - base
    ports:
      - 3002:3002

networks:
  base:
    name: base-network

volumes:
  mongodb:
  mongodb-cfg:
